# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_S_seprt <- function(S, X, A, beta, group, q, p, K, G, n) {
    invisible(.Call('_nlss_update_S_seprt', PACKAGE = 'nlss', S, X, A, beta, group, q, p, K, G, n))
}

sum_subset2 <- function(a, q, n, nonzero) {
    .Call('_nlss_sum_subset2', PACKAGE = 'nlss', a, q, n, nonzero)
}

sum_subset3 <- function(a, q, n, nonzero) {
    .Call('_nlss_sum_subset3', PACKAGE = 'nlss', a, q, n, nonzero)
}

update_S_joint <- function(S, X, A, q, p, K, n, Sspace, states, stat_link, ns, q0) {
    invisible(.Call('_nlss_update_S_joint', PACKAGE = 'nlss', S, X, A, q, p, K, n, Sspace, states, stat_link, ns, q0))
}

findmode_S <- function(S, X, A, beta, group, q, p, K, G, n) {
    invisible(.Call('_nlss_findmode_S', PACKAGE = 'nlss', S, X, A, beta, group, q, p, K, G, n))
}

update_A <- function(A, X, Y, alpha_1, alpha_0, q, p, n, seed, seed2) {
    invisible(.Call('_nlss_update_A', PACKAGE = 'nlss', A, X, Y, alpha_1, alpha_0, q, p, n, seed, seed2))
}

update_Y <- function(Y, X, A, S, seed, q, p, n, K) {
    invisible(.Call('_nlss_update_Y', PACKAGE = 'nlss', Y, X, A, S, seed, q, p, n, K))
}

NLSS_gibbs_sampler <- function(X, A0, S0, Y0, stat_link, joint, alpha, Sspace, states, q0, K, total_iter = 1000L, burn_in = 100L, thin = 10L, show_step = 50L) {
    .Call('_nlss_NLSS_gibbs_sampler', PACKAGE = 'nlss', X, A0, S0, Y0, stat_link, joint, alpha, Sspace, states, q0, K, total_iter, burn_in, thin, show_step)
}

simNLSS <- function(S, A, K) {
    .Call('_nlss_simNLSS', PACKAGE = 'nlss', S, A, K)
}

NLSS_logLik_noise0 <- function(X, S, A, K) {
    .Call('_nlss_NLSS_logLik_noise0', PACKAGE = 'nlss', X, S, A, K)
}

