# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Simu_DLSS <- function(S, A, K) {
    .Call('_nlss_Simu_DLSS', PACKAGE = 'nlss', S, A, K)
}

Simu_data_bi <- function(X, mu0, sd0, th) {
    .Call('_nlss_Simu_data_bi', PACKAGE = 'nlss', X, mu0, sd0, th)
}

DLSS_Deviance_c <- function(X, S, A, K) {
    .Call('_nlss_DLSS_Deviance_c', PACKAGE = 'nlss', X, S, A, K)
}

DLSS_logLik_noisefree <- function(X, S, A, K) {
    .Call('_nlss_DLSS_logLik_noisefree', PACKAGE = 'nlss', X, S, A, K)
}

DLSS_logLik_noise <- function(X, S, A, K) {
    .Call('_nlss_DLSS_logLik_noise', PACKAGE = 'nlss', X, S, A, K)
}

parallelDLSS_update_Y_n <- function(Y, X, A, S, seed, q, p, n, K) {
    invisible(.Call('_nlss_parallelDLSS_update_Y_n', PACKAGE = 'nlss', Y, X, A, S, seed, q, p, n, K))
}

parallelDLSS_update_S_n <- function(S, loglik, X, A, beta, u, sampS_star, q, p, K, n) {
    invisible(.Call('_nlss_parallelDLSS_update_S_n', PACKAGE = 'nlss', S, loglik, X, A, beta, u, sampS_star, q, p, K, n))
}

parallelDLSS_update_A_n <- function(A, X, Y, alpha_1, alpha_0, q, p, n, seed, seed2) {
    invisible(.Call('_nlss_parallelDLSS_update_A_n', PACKAGE = 'nlss', A, X, Y, alpha_1, alpha_0, q, p, n, seed, seed2))
}

DLSS_gibbs_sampler_n <- function(X, A0, gamma, alpha, total_iter = 1000L, burn_in = 100L, show_step = 50L) {
    .Call('_nlss_DLSS_gibbs_sampler_n', PACKAGE = 'nlss', X, A0, gamma, alpha, total_iter, burn_in, show_step)
}

